### ISSUE TITLE
Adding gradient to menubar.

### ISSUE THREAD

**Issue by SirWindfield** [katacarbix/windowbar#3]
Fairly new to js stack. Is it possible to add a custom gradient to the windowbar like macOS does it? It would make it easier to merge the windowbar with a custom toolbar that sits right below it. 
<img width="769" alt="example" src="https://user-images.githubusercontent.com/5113257/33453376-aaa48bfa-d615-11e7-9a65-89e7bb88e45f.png">

**Comment by katacarbix** [comment]
There are many ways you can achieve this now using a mix of constructor options and CSS.
